-- MySQL Script generated by MySQL Workbench
-- Sun May 27 02:29:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema LibraryDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LibraryDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LibraryDB` DEFAULT CHARACTER SET utf8 ;
USE `LibraryDB` ;

-- -----------------------------------------------------
-- Table `LibraryDB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryDB`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` CHAR(40) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `role` INT NOT NULL COMMENT 'Три роли:\n0 librarian\n1 reader \n2 supplier',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryDB`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryDB`.`Book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `author` VARCHAR(100) NOT NULL,
  `publisher` VARCHAR(100) NOT NULL,
  `publish_year` INT NOT NULL,
  `status` INT NOT NULL COMMENT 'Три статуса:\n0 - library\n1 - exchange\n2 - order',
  `condition` INT NOT NULL COMMENT 'Состояния:\n0 - in_library\n1 - in_reading\n2 - not_available\n3 - returned_to_owner\n4 - on_exchange\n5 - order_in_progress',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryDB`.`OrderBooks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryDB`.`OrderBooks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_OrderBooks_Book1_idx` (`book_id` ASC),
  INDEX `fk_OrderBooks_User1_idx` (`supplier_id` ASC),
  CONSTRAINT `fk_OrderBooks_Book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `LibraryDB`.`Book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderBooks_User1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `LibraryDB`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryDB`.`LibraryBooks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryDB`.`LibraryBooks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `reader_id` INT NOT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LibraryBooks_Book1_idx` (`book_id` ASC),
  INDEX `fk_LibraryBooks_User1_idx` (`reader_id` ASC),
  CONSTRAINT `fk_LibraryBooks_Book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `LibraryDB`.`Book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LibraryBooks_User1`
    FOREIGN KEY (`reader_id`)
    REFERENCES `LibraryDB`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryDB`.`ExchangeBooks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryDB`.`ExchangeBooks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `owner_id` INT NOT NULL,
  `reader_id` INT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ExchangeBooks_Book1_idx` (`book_id` ASC),
  INDEX `fk_ExchangeBooks_User1_idx` (`owner_id` ASC),
  INDEX `fk_ExchangeBooks_User2_idx` (`reader_id` ASC),
  CONSTRAINT `fk_ExchangeBooks_Book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `LibraryDB`.`Book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExchangeBooks_User1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `LibraryDB`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExchangeBooks_User2`
    FOREIGN KEY (`reader_id`)
    REFERENCES `LibraryDB`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `LibraryDB`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `LibraryDB`;
INSERT INTO `LibraryDB`.`User` (`id`, `login`, `password`, `name`, `role`) VALUES (0, 'main', '011c945f30ce2cbafc452f39840f025693339c42', 'Oleynik Maxim', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `LibraryDB`.`Book`
-- -----------------------------------------------------
START TRANSACTION;
USE `LibraryDB`;
INSERT INTO `LibraryDB`.`Book` (`id`, `title`, `author`, `publisher`, `publish_year`, `status`, `condition`) VALUES (0, 'Good Book 01', 'Author 01', 'Publisher 01', 1991, 0, 0);
INSERT INTO `LibraryDB`.`Book` (`id`, `title`, `author`, `publisher`, `publish_year`, `status`, `condition`) VALUES (1, 'Book 01', 'Author 02', 'Publisher 02', 1965, 0, 0);

COMMIT;

